### ISSUE TITLE
Losing scripting.as file during track upload

### ISSUE THREAD

**Issue by SvenAndreasBelting** [supertuxkart/stk-addons#107]
If you upload a track containing a scripting.as file, the latter will be removed from the uploaded track. The following error message will be displayed: "Some invalid files were found in the uploaded add-on. These files have been removed from the archive: scripting.as."

 As a consequence several features will not be available, such as showing objects used only in reverse mode.

**Comment by auriamg** [comment]
This should now be fixed, can you try again?

**Comment by SvenAndreasBelting** [comment]
I have tried again but it's still the same. The error message will be displayed, and also the file is missing in the downloaded track.

**Comment by auriamg** [comment]
@leyyin Can you check what i did wrong with my fix? I thought this would work

**Comment by auriamg** [comment]
@SvenAndreasBelting ok sorry for the failed attempt, I think this time I got it right

**Comment by leyyin** [comment]
After your last commit it should work.

**Comment by SvenAndreasBelting** [comment]
Yes it works. Thank you very much!

But I can't upload the source file because it is too big (135 MB). 
What should I do?

**Comment by leyyin** [comment]
The maximum file size is 35 MB, why is your addon so large?

**Comment by SvenAndreasBelting** [comment]
I meant the blend file. The addon itself works fine (it's already uploaded).

**Comment by auriamg** [comment]
@SvenAndreasBelting the question still holds though, 35 MB is a bit low but 135 is surprisingly large

**Comment by qwertychouskie** [comment]
The bug is fixed and the source uploaded, can this be closed?
